language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script: wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: composer install && php mageekguy.atoum.phar -c coverage.php -d tests/units/
